---
name: cds102labs
channels:
  - defaults
  - conda-forge
  - jkglasbrenner
dependencies:
  - anaconda=custom
  - git=2.18.0
  - pandoc=2.2.1
  - pelican=3.7.1
  - python=3.6
  - markdown=2.6.11
  - typogrify=2.0.7
  - rpy2
  - r-base
  - r-commonmark
  - r-devtools
  - r-essentials
  - r-fs
  - r-git2r
  - r-lintr
  - r-nycflights13
  - r-tidyverse
  - r-vembedr
...
