Title: Exploration by visualization\: the Galton dataset
Author: Dr. Glasbrenner
Author_Image: https://www.gravatar.com/avatar/49802fdfa5a0e63b3d932a5179d41c1e
Date: 2018-05-29 13:30
Tags: lab
Slug: lab-02-exploration-by-visualization-the-galton-dataset
Summary: Explore the Galton dataset using data visualization.
Show_summary: true
Show_link: true

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, fig.width = 6, warning = FALSE,
  message = FALSE, dev = "svg",
  fig.asp = 0.618, out.width = "80%", dpi = 120,
  fig.align = "center", cache = FALSE
)
library(tidyverse)

icon_pdf <- '<i class="fas fa-file-pdf" data-fa-transform="grow-16"></i>&nbsp;'
icon_github <- '<i class="fab fa-github-alt" data-fa-transform="grow-16"></i>&nbsp;'
```

> This week’s lab shows you how to use the ggplot2 package to visualize datasets and how visualization plays a crucial role in data exploration.

## How to submit

When you are ready to submit, be sure to save, commit, and push your final result so that everything is synchronized to Github.
Then, navigate to **your copy** of the Github repository you used for this assignment.
You should see your repository, along with the updated files that you just synchronized to Github.
Confirm that your files are up-to-date, and then do the following steps:

:::::{.pull-request}
*   Click the *Pull Requests* tab near the top of the page.

*   Click the green button that says "New pull request".

*   Click the dropdown menu button labeled "base:", and select the option `starting`.

*   Confirm that the dropdown menu button labeled "compare:" is set to `master`.

*   Click the green button that says "Create pull request".

*   Give the *pull request* the following title: [Submission: Lab 2, FirstName LastName]{.monospace}, replacing [FirstName]{.monospace} and [LastName]{.monospace} with your actual first and last name.

*   In the messagebox, write: [My lab report is ready for grading \@jkglasbrenner]{.monospace}.

*   Click "Create pull request" to lock in your submission.
:::::

## Credits

This lab is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).
[The description of the [Galton]{.monospace} dataset](#about-the-galton-dataset) was adapted from the documentation of the same dataset that’s available in the [[mosaicData]{.monospace} R package](https://github.com/ProjectMOSAIC/mosaicData) and some of the lab exercises were adapted from problem sets found in *Modern Data Science with R* by Benjamin Baumer, Daniel Kaplan, and Nicholas Horton.
All other exercises and instructions written by James Glasbrenner for CDS-102.

